# Generated by Django 4.0.4 on 2022-05-17 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit', '0004_alter_post_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
