# Generated by Django 4.0.4 on 2022-06-03 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit', '0017_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='temporary_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
